name: 'terraform-workflow'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'terraform-job'
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v3

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: 'Configure AWS Credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: 'Terraform Init'
      run: 
        terraform main.tf
        terraform init

    - name: 'Terraform Format Check'
      run: 
        terraform main.tf
        terraform fmt -check

    - name: 'Terraform Plan'
      run: 
        terraform main.tf
        terraform plan -input=false

    - name: 'Terraform Apply'
      run: 
        terraform main.tf
        terraform apply -auto-approve -input=false
